version: '3'

services:
  db:
    build:
      dockerfile: ./docker/files/Dockerfile.postgres
      context: "../"
    container_name: library_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=library_db